#!/usr/bin/env python3
"""Generate Localizable.strings for every language from the JSON maps.

Usage: gen-l10n.py <l10n-dir> <resources-dir>
The l10n dir holds one <lang>.json per language with English keys and
translated values. The en table repeats the keys as values. Every language
must cover exactly the key set of es.json; a mismatch stops the build.
"""
import json
import sys
from pathlib import Path


def load_strict(path: Path) -> dict[str, str]:
    """Parse a JSON map and stop on duplicate keys.

    json.loads keeps only the last duplicate silently. A duplicate key means
    one English text carries two meanings and must be disambiguated in code.
    """
    duplicates: list[str] = []

    def check(pairs):
        seen: dict[str, str] = {}
        for key, value in pairs:
            if key in seen:
                duplicates.append(key)
            seen[key] = value
        return seen

    data = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=check)
    if duplicates:
        print(f"{path.name}: duplicate keys {sorted(set(duplicates))}")
        sys.exit(1)
    return data


def esc(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_strings(path: Path, pairs: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by scripts/gen-l10n.py. Edit the JSON maps, not this file. */"]
    for key in sorted(pairs):
        lines.append(f'"{esc(key)}" = "{esc(pairs[key])}";')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    l10n_dir, resources = Path(sys.argv[1]), Path(sys.argv[2])
    canonical = set(load_strict(l10n_dir / "es.json"))

    failures = []
    languages = sorted(l10n_dir.glob("*.json"))
    for lang_file in languages:
        mapping = load_strict(lang_file)
        missing = canonical - set(mapping)
        extra = set(mapping) - canonical
        empty = [k for k, v in mapping.items() if not v]
        if missing or extra or empty:
            failures.append(f"{lang_file.name}: missing={sorted(missing)} extra={sorted(extra)} empty={sorted(empty)}")
            continue
        write_strings(resources / f"{lang_file.stem}.lproj/Localizable.strings", mapping)

    write_strings(resources / "en.lproj/Localizable.strings", {k: k for k in canonical})

    if failures:
        print("Key set mismatches against es.json:")
        print("\n".join(failures))
        sys.exit(1)
    print(f"Wrote {len(canonical)} keys for en + {[f.stem for f in languages]}")


if __name__ == "__main__":
    main()
